#!/bin/bash
set -e

ContainerFilter=$(cat <<EOF
.Created+60*60<now
EOF
)

ImageFilter=$(cat <<EOF
.Created+60*60<now
and (
        (.RepoTags | contains(["buildkite"]))
        or
        (.RepoTags | contains(["none"]))
)
EOF
)

NetworkFilter=$(cat <<EOF
.Created+60*60<now
and (.Name | contains("buildkite"))
EOF
)

# try gentle first
# stop containers
docker-purge --containers --container.kill="9" "$ContainerFilter"
docker-purge --containers "$ContainerFilter"
docker-purge --images "$ImageFilter"
docker-purge --networks "$NetworkFilter"


docker-purge --force --all --containers "$ContainerFilter"
docker-purge --force --all --images "$ImageFilter"
docker-purge --force --all --networks "$NetworkFilter"

logger -t docker-gc Cleaned Containers, Images and Networks
