#!/bin/bash
set -e



filter=$(cat <<EOF
.Created+60*60<now
and (
        (.RepoTags | contains(["buildkite"]))
        or
        (.RepoTags | contains(["none"]))
)
EOF
)

# try gentle first
docker-purge --containers '.Created+60*60<now'
docker-purge --images "$filter"
docker-purge --networks '.Created+60*60<now'


docker-purge --force --all --containers '.Created+60*60<now'
docker-purge --force --all --images "$filter"
docker-purge --force --all --networks '.Created+60*60<now'

logger -t docker-gc Cleaned Containers, Images and Networks
